DROP TABLE BOOK;
DROP TABLE OLD_BOOK;
DROP TABLE MEMBER;
DROP SEQUENCE OLD_BOOK_SEQ;

--중고책 시퀀스(PK)
CREATE SEQUENCE OLD_BOOK_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE BOOK 
(
  TITLE VARCHAR2(40) NOT NULL 
, WRITER VARCHAR2(20) NOT NULL 
, PUBLISHER VARCHAR2(20) NOT NULL 
, PUBLISH_DATE DATE NOT NULL 
, STOCK NUMBER DEFAULT 0 NOT NULL 
, PRICE NUMBER NOT NULL
, GENRE VARCHAR2(20) NOT NULL
, TRANSLATOR VARCHAR2(20)
, REVIEW1 VARCHAR2(150)
, REVIEW2 VARCHAR2(150)
, IMAGE BLOB
, CONSTRAINT BOOK_PK PRIMARY KEY 
  (
    TITLE 
  )
  ENABLE 
);

CREATE TABLE OLD_BOOK 
(
  NUM NUMBER NOT NULL 
, TITLE VARCHAR2(40) NOT NULL 
, WRITER VARCHAR2(20) NOT NULL 
, PUBLISHER VARCHAR2(20) NOT NULL 
, PUBLISH_DATE DATE NOT NULL 
, PRICE NUMBER NOT NULL 
, GENRE VARCHAR2(20) NOT NULL
, SELLER VARCHAR2(20) NOT NULL 
, BUYER VARCHAR2(20)
, STATUS VARCHAR2(10)
, CONSTRAINT OLD_BOOK_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);

CREATE TABLE MEMBER 
(
  ID VARCHAR2(30) NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, TEL VARCHAR2(20) NOT NULL 
, EMAIL VARCHAR2(40) NOT NULL 
, ADDRESS VARCHAR2(100) 
, PW VARCHAR2(50) NOT NULL 
, PWCHK VARCHAR2(50) NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

--중고책 시퀀스 테이블에 부여
CREATE TRIGGER OLD_BOOK_TRG 
BEFORE INSERT ON OLD_BOOK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NUM IS NULL THEN
      SELECT OLD_BOOK_SEQ.NEXTVAL INTO :NEW.NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

INSERT INTO BOOK (TITLE, WRITER, PUBLISHER, PUBLISH_DATE, PRICE, GENRE, REVIEW1) VALUES ('기억전달자', '로이스 로리', '비룡소', TO_DATE('2007-05-18', 'YYYY-MM-DD'), '9900', '문학', '쉽게읽어내려갈수있고 많은 생각과 여운이 남았습니다~촉촉함의 감성도느낄수 있는 책이였어요~~');
INSERT INTO MEMBER (ID, NAME, TEL, EMAIL, ADDRESS,PW,PWCHK) VALUES ('admin', '관리자', '010-9800-4126', 's2017s16@e-mirim.hs.kr', '서울특별시 금천구','1234qwer!','1234qwer!');
INSERT INTO OLD_BOOK (TITLE, WRITER, PUBLISHER, PUBLISH_DATE, PRICE, GENRE, SELLER) VALUES ('아낌없이 주는 나무', '셸 실버스타인', '시공주니어', TO_DATE('2000-11-30', 'YYYY-MM-DD'), '4500', '문학', 'dlwngus');

SELECT * FROM BOOK;
SELECT * FROM OLD_BOOK;
SELECT * FROM MEMBER;