-- USER SQL
CREATE USER "DORAN" IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "DORAN" QUOTA 8M ON "USERS";

-- ROLES
GRANT "DBA" TO "DORAN" ;
GRANT "CONNECT" TO "DORAN" ;
GRANT "RESOURCE" TO "DORAN" ;

-- SYSTEM PRIVILEGES