/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-07-31 07:58:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class booklist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<form method=\"post\" enctype=\"multipart/form-data\" action=\"booklist_ok.jsp\">\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"500\">\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td width=\"150\">\r\n");
      out.write("  분류선택\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=\"350\" align=\"left\">\r\n");
      out.write("  <select name=\"bookstri\">\r\n");
      out.write("   <option value=\"컴퓨터\">컴퓨터</option>\r\n");
      out.write("   <option value=\"수험서\">수험서</option>\r\n");
      out.write("   <option value=\"소설\">소설</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>제목</td>\r\n");
      out.write("  <td align=\"left\"><input type=\"text\" name=\"title\" size=\"30\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>가격</td>\r\n");
      out.write("  <td align=\"left\"><input type=\"text\" name=\"price\" size=\"10\">원</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>수량</td>\r\n");
      out.write("  <td align=\"left\"><input type=\"text\" name=\"quantity\" size=\"10\">권</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>저자</td>\r\n");
      out.write("  <td align=\"left\"><input type=\"text\" name=\"writer\" size=\"30\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>출판사</td>\r\n");
      out.write("  <td align=\"left\"><input type=\"text\" name=\"publcom\" size=\"30\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>출판일</td>\r\n");
      out.write("  <td align=\"left\">\r\n");
      out.write("  <select name=\"year\">\r\n");
 for(int year=2000;year<2011;year++){
      out.write("\r\n");
      out.write("   <option value=\"");
      out.print(year );
      out.write('"');
      out.write('>');
      out.print(year );
      out.write("</option>\r\n");
} 
      out.write("\r\n");
      out.write("  </select>\r\n");
      out.write("  <select name=\"m\">\r\n");
 for(int m=1;m<13;m++){
      out.write("\r\n");
      out.write("   <option value=\"");
      out.print(m );
      out.write('"');
      out.write('>');
      out.print(m );
      out.write("</option>\r\n");
} 
      out.write("\r\n");
      out.write("  </select>\r\n");
      out.write("  <select name=\"d\">\r\n");
 for(int d=1;d<32;d++){
      out.write("\r\n");
      out.write("   <option value=\"");
      out.print(d );
      out.write('"');
      out.write('>');
      out.print(d );
      out.write("</option>\r\n");
} 
      out.write("\r\n");
      out.write("  </select>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>이미지</td>\r\n");
      out.write("  <td align=\"left\"><input type=\"file\" name=\"bookimg\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>내용</td>\r\n");
      out.write("  <td align=\"left\">\r\n");
      out.write("  <textarea name=\"text\"></textarea>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>할인율</td>\r\n");
      out.write("  <td align=\"left\"><input type=\"text\" name=\"discount\" size=\"10\">%</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td colspan=\"2\"><input type=\"submit\" value=\"책등록\"><input type=\"reset\" value=\"다시작성\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
