/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-08-28 00:52:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oldBookEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>도란도란 : 책 등록</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bookEnroll.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Sunflower:300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script>\r\n");
      out.write("    \twindow.onload=function(){\r\n");
      out.write("    \t\tdocument.form.title.focus();\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction check(){\r\n");
      out.write("\t\t\t/*if(document.form.id.value==\"\"){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t\tdocument.form.id.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(document.form.pw.value==\"\"){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t\tdocument.form.pw.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}*/\r\n");
      out.write("\t\t\tdocument.forms['form'].submit();\t//아이디, 비밀번호 다 입력했을 시 loginProc.jsp로 이동\r\n");
      out.write("\t\t}//function check()\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("<p><br>\r\n");
      out.write("<form name=\"form\" action=\"oldBookEnrollProc.jsp\" method=\"post\">\r\n");
      out.write("    <table id=\"whole\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td colspan=3>\r\n");
      out.write("               <div id=\"box\" align=\"center\">\r\n");
      out.write("                   <h1>중고 책 등록하기</h1>\r\n");
      out.write("                   <p/>\r\n");
      out.write("                   <table>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                         \t<td>\r\n");
      out.write("                               <font size=\"5%\">제목</font>\r\n");
      out.write("                         \t </td>\r\n");
      out.write("                         \t<td>\r\n");
      out.write("                              <input type=\"text\" name=\"title\" class=\"text\" size=30><p>\r\n");
      out.write("                       \t    </td>\r\n");
      out.write("                      \t\t<td width=\"10%\"></td>\r\n");
      out.write("                      \t\t<td>\r\n");
      out.write("                               <font size=\"5%\">이미지</font>\r\n");
      out.write("                          \t</td>\r\n");
      out.write("                      \t\t<td>\r\n");
      out.write("                              <input type=\"file\" name=\"image\"><p>\r\n");
      out.write("                          \t</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\t\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <font size=\"5%\">작가</font>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" name=\"writer\" class=\"text\" size=30><p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td width=\"10%\"></td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                               <font size=\"5%\">장르</font>\r\n");
      out.write("                          \t</td>\r\n");
      out.write("                      \t\t<td>\r\n");
      out.write("                              <select name=\"genre\">\r\n");
      out.write("                              \t<option value=\"null\" selected>----- 선택 -----</option>\r\n");
      out.write("                              \t<option value=0>총류</option>\r\n");
      out.write("                              \t<option value=1>철학</option>\r\n");
      out.write("                              \t<option value=2>종교</option>\r\n");
      out.write("                              \t<option value=3>사회과학</option>\r\n");
      out.write("                              \t<option value=4>순수과학</option>\r\n");
      out.write("                              \t<option value=5>기술과학</option>\r\n");
      out.write("                              \t<option value=6>예술</option>\r\n");
      out.write("                              \t<option value=7>언어</option>\r\n");
      out.write("                              \t<option value=8>문학</option>\r\n");
      out.write("                              \t<option value=9>역사</option>\r\n");
      out.write("                              </select><p>\r\n");
      out.write("                          \t</td>\r\n");
      out.write("                       </tr>\r\n");
      out.write("                       <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <font size=\"5%\">출판사</font>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" name=\"publisher\" class=\"text\" size=30><p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td width=\"10%\"></td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <font size=\"5%\">출판일</font>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"date\" name=\"publish_date\" class=\"text\" size=30><p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                       <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <font size=\"5%\">가격</font>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" name=\"price\" class=\"text\" size=30><p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td width=\"10%\"></td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <font size=\"5%\">옮긴이</font>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" name=\"translator\" class=\"text\" size=30><p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                       </tr>\r\n");
      out.write("                       <tr>\r\n");
      out.write("                           <td colspan=5 align=\"center\">\r\n");
      out.write("                           \t<p>\r\n");
      out.write("                           \t<input type=\"button\" id=\"enroll\" class=\"btn\" value=\"등록하기\" onclick=\"check()\">\r\n");
      out.write("                           \t<p>\r\n");
      out.write("                           </td>\r\n");
      out.write("                       </tr>\r\n");
      out.write("                   </table>\r\n");
      out.write("               </div>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
